#!/usr/bin/env bash
# ============================================================
# Pi³ — Demo Day Startup Script (YOUR Pi — Rpi4 Database & GUI)
# Done By : Saim Hashmi
#
# Run this on YOUR Raspberry Pi 4 to start everything:
#   chmod +x start_server.sh
#   ./start_server.sh
#
# This starts:
#   1. FastAPI backend on port 8000
#   2. Frontend dev server on port 5173 (accessible from any device on LAN)
#
# Prerequisites:
#   - Python 3.11+ with venv
#   - Node.js 18+
#   - npm
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "  ╔═══════════════════════════════════════════════╗"
echo "  ║           Pi³ Rubik's Cube Solver             ║"
echo "  ║          Demo Day — Server Startup            ║"
echo "  ╚═══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Get this Pi's IP ────────────────────────────────────────
MY_IP=$(hostname -I | awk '{print $1}')
echo -e "${BLUE}📡 Your Pi's IP address: ${GREEN}${MY_IP}${NC}"
echo -e "${BLUE}   Tell your teammates to set: ${YELLOW}PI_SERVER_IP=${MY_IP}${NC}"
echo ""

# ── Check prerequisites ────────────────────────────────────
echo -e "${BLUE}🔍 Checking prerequisites...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Python 3 not found. Install it first.${NC}"
    exit 1
fi
echo -e "   ${GREEN}✓${NC} Python $(python3 --version 2>&1 | cut -d' ' -f2)"

if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js not found. Install it first.${NC}"
    exit 1
fi
echo -e "   ${GREEN}✓${NC} Node $(node --version)"

if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm not found. Install it first.${NC}"
    exit 1
fi
echo -e "   ${GREEN}✓${NC} npm $(npm --version 2>/dev/null)"

# ── Setup Python venv ──────────────────────────────────────
echo ""
echo -e "${BLUE}🐍 Setting up Python environment...${NC}"

if [ ! -d ".venv" ]; then
    echo "   Creating virtual environment..."
    python3 -m venv .venv
fi

source .venv/bin/activate
pip install -q -r requirements.txt 2>/dev/null
echo -e "   ${GREEN}✓${NC} Python dependencies installed"

# ── Setup Frontend ─────────────────────────────────────────
echo ""
echo -e "${BLUE}⚛️  Setting up frontend...${NC}"

cd frontend
if [ ! -d "node_modules" ]; then
    echo "   Installing npm packages (first time only, may take a few minutes)..."
    npm install 2>&1 | tail -3
fi
echo -e "   ${GREEN}✓${NC} Frontend dependencies ready"
cd ..

# ── Write .env for this Pi ─────────────────────────────────
cat > .env <<EOF
# Pi³ Server Configuration (auto-generated by start_server.sh)
PI_SERVER_IP=localhost
PI_SERVER_PORT=8000
NODE_ID=rpi4-db
NODE_TYPE=database
HEARTBEAT_INTERVAL=3
DATABASE_URL=./rubiks.db
EOF
echo -e "   ${GREEN}✓${NC} .env configured for Database & GUI Pi"

# ── Kill any existing processes on our ports ───────────────
echo ""
echo -e "${BLUE}🧹 Cleaning up old processes...${NC}"

if command -v lsof &> /dev/null; then
    lsof -ti :8000 | xargs kill 2>/dev/null || true
    lsof -ti :5173 | xargs kill 2>/dev/null || true
else
    fuser -k 8000/tcp 2>/dev/null || true
    fuser -k 5173/tcp 2>/dev/null || true
fi
sleep 1
echo -e "   ${GREEN}✓${NC} Ports cleared"

# ── Start Backend ──────────────────────────────────────────
echo ""
echo -e "${BLUE}🚀 Starting backend server...${NC}"

source .venv/bin/activate
uvicorn backend.main:app --host 0.0.0.0 --port 8000 > /tmp/pi3-backend.log 2>&1 &
BACKEND_PID=$!
sleep 2

if kill -0 $BACKEND_PID 2>/dev/null; then
    echo -e "   ${GREEN}✓${NC} Backend running on port 8000 (PID: $BACKEND_PID)"
else
    echo -e "   ${RED}❌ Backend failed to start. Check /tmp/pi3-backend.log${NC}"
    exit 1
fi

# ── Start Frontend ─────────────────────────────────────────
echo ""
echo -e "${BLUE}🌐 Starting frontend server...${NC}"

cd frontend
npm run dev -- --host 0.0.0.0 > /tmp/pi3-frontend.log 2>&1 &
FRONTEND_PID=$!
cd ..
sleep 3

if kill -0 $FRONTEND_PID 2>/dev/null; then
    echo -e "   ${GREEN}✓${NC} Frontend running on port 5173 (PID: $FRONTEND_PID)"
else
    echo -e "   ${RED}❌ Frontend failed to start. Check /tmp/pi3-frontend.log${NC}"
    kill $BACKEND_PID 2>/dev/null
    exit 1
fi

# ── Print summary ──────────────────────────────────────────
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Pi³ Server is running!${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BLUE}Dashboard:${NC}      http://${MY_IP}:5173"
echo -e "  ${BLUE}API:${NC}            http://${MY_IP}:8000"
echo -e "  ${BLUE}API Health:${NC}     http://${MY_IP}:8000/"
echo ""
echo -e "  ${YELLOW}📋 For your teammates:${NC}"
echo -e "     Set ${GREEN}PI_SERVER_IP=${MY_IP}${NC} in their .env"
echo -e "     Then run ${GREEN}./start_node.sh${NC} on their Pi"
echo ""
echo -e "  ${YELLOW}📱 Open dashboard on any device:${NC}"
echo -e "     http://${MY_IP}:5173"
echo ""
echo -e "  ${YELLOW}📄 Logs:${NC}"
echo -e "     Backend:  tail -f /tmp/pi3-backend.log"
echo -e "     Frontend: tail -f /tmp/pi3-frontend.log"
echo ""
echo -e "  Press ${RED}Ctrl+C${NC} to stop everything"
echo ""

# ── Trap Ctrl+C to clean up ────────────────────────────────
cleanup() {
    echo ""
    echo -e "${YELLOW}🛑 Shutting down...${NC}"
    kill $BACKEND_PID 2>/dev/null
    kill $FRONTEND_PID 2>/dev/null
    echo -e "${GREEN}   Done. Goodbye!${NC}"
    exit 0
}

trap cleanup SIGINT SIGTERM

# ── Keep script alive until Ctrl+C ─────────────────────────
wait $BACKEND_PID $FRONTEND_PID
