-- ============================================================
-- SYSC3010 L3-G6 Rubik's Cube Solver — Database Schema
-- Target: SQLite (local dev) / Supabase PostgreSQL (production)
-- ============================================================

-- Users authenticated to operate the solver
CREATE TABLE IF NOT EXISTS users (
    id          INTEGER     PRIMARY KEY AUTOINCREMENT,
    username    VARCHAR     NOT NULL,
    role        VARCHAR     NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Live status of each Raspberry Pi node
CREATE TABLE IF NOT EXISTS node_status (
    node_id         VARCHAR     PRIMARY KEY,
    node_type       VARCHAR     NOT NULL,
    ip_address      VARCHAR,
    status          VARCHAR     NOT NULL,
    last_heartbeat  TIMESTAMP   NOT NULL,
    last_message    TEXT
);

-- Top-level record for each cube-solve attempt
CREATE TABLE IF NOT EXISTS solve_sessions (
    id                  INTEGER     PRIMARY KEY AUTOINCREMENT,
    user_id             INTEGER     REFERENCES users(id),
    session_name        VARCHAR,
    selected_algorithm  VARCHAR     NOT NULL,
    status              VARCHAR     NOT NULL,
    started_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        TIMESTAMP,
    notes               TEXT
);

-- Cube state strings produced by the scanner or solver
CREATE TABLE IF NOT EXISTS cube_states (
    id          INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id  INTEGER     NOT NULL REFERENCES solve_sessions(id),
    source      VARCHAR     NOT NULL,
    state_string VARCHAR    NOT NULL,
    is_valid    BOOLEAN     NOT NULL,
    confidence  REAL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Individual face scans captured by Rpi1
CREATE TABLE IF NOT EXISTS scan_faces (
    id          INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id  INTEGER     NOT NULL REFERENCES solve_sessions(id),
    face_name   VARCHAR     NOT NULL,
    face_string VARCHAR     NOT NULL,
    confidence  REAL,
    captured_by VARCHAR,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Solution move sequences generated by Rpi2
CREATE TABLE IF NOT EXISTS solutions (
    id              INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id      INTEGER     NOT NULL REFERENCES solve_sessions(id),
    algorithm_used  VARCHAR     NOT NULL,
    move_count      INTEGER     NOT NULL,
    solution_string TEXT,
    generated_by    VARCHAR,
    generated_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Individual moves within a solution
CREATE TABLE IF NOT EXISTS solution_steps (
    id          INTEGER     PRIMARY KEY AUTOINCREMENT,
    solution_id INTEGER     NOT NULL REFERENCES solutions(id),
    step_index  INTEGER     NOT NULL,
    face        VARCHAR     NOT NULL,
    direction   VARCHAR     NOT NULL,
    degrees     INTEGER     NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Physical execution attempts by Rpi3
CREATE TABLE IF NOT EXISTS execution_runs (
    id              INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id      INTEGER     NOT NULL REFERENCES solve_sessions(id),
    solution_id     INTEGER     NOT NULL REFERENCES solutions(id),
    status          VARCHAR     NOT NULL,
    started_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP,
    motor_node_id   VARCHAR
);

-- Per-step motor execution log
CREATE TABLE IF NOT EXISTS motor_execution_log (
    id              INTEGER     PRIMARY KEY AUTOINCREMENT,
    run_id          INTEGER     NOT NULL REFERENCES execution_runs(id),
    step_index      INTEGER     NOT NULL,
    commanded_face  VARCHAR     NOT NULL,
    commanded_dir   VARCHAR     NOT NULL,
    commanded_deg   INTEGER     NOT NULL,
    status          VARCHAR     NOT NULL,
    error_code      VARCHAR,
    error_message   TEXT,
    ts              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Post-execution cube verification results
CREATE TABLE IF NOT EXISTS verification_results (
    id                  INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id          INTEGER     NOT NULL REFERENCES solve_sessions(id),
    run_id              INTEGER     REFERENCES execution_runs(id),
    verified            BOOLEAN     NOT NULL,
    final_state_string  VARCHAR,
    method              VARCHAR     NOT NULL,
    notes               TEXT,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Distributed system event log from all nodes
CREATE TABLE IF NOT EXISTS system_logs (
    id          INTEGER     PRIMARY KEY AUTOINCREMENT,
    session_id  INTEGER     REFERENCES solve_sessions(id),
    node_id     VARCHAR     REFERENCES node_status(node_id),
    level       VARCHAR     NOT NULL,
    event_type  VARCHAR     NOT NULL,
    message     TEXT        NOT NULL,
    metadata    TEXT,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
