#!/usr/bin/env bash
# ============================================================
# Pi³ — Demo Day Startup Script (TEAMMATE Pi — Scanner/Solver/Motor)
# Done By : Saim Hashmi
#
# Run this on a teammate's Raspberry Pi:
#   chmod +x start_node.sh
#   ./start_node.sh
#
# Before running, either:
#   a) Set the server IP when prompted, OR
#   b) Create a .env file with PI_SERVER_IP=<saim's pi ip>
#
# This will:
#   1. Auto-detect which node type this Pi is (or ask)
#   2. Send heartbeats to the central server
#   3. Run the node's subsystem code
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "  ╔═══════════════════════════════════════════════╗"
echo "  ║           Pi³ Rubik's Cube Solver             ║"
echo "  ║          Demo Day — Node Startup              ║"
echo "  ╚═══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Load .env if it exists ─────────────────────────────────
if [ -f .env ]; then
    export $(grep -v '^#' .env | grep -v '^$' | xargs)
    echo -e "${GREEN}✓${NC} Loaded .env file"
fi

# ── Get server IP ──────────────────────────────────────────
if [ -z "$PI_SERVER_IP" ]; then
    echo -e "${YELLOW}🔧 Server IP not set.${NC}"
    echo -e "   Enter the IP address of Saim's Pi (Rpi4 — the server):"
    echo -e "   (Saim: run ${GREEN}hostname -I${NC} on your Pi to find it)"
    echo ""
    read -p "   Server IP: " PI_SERVER_IP

    if [ -z "$PI_SERVER_IP" ]; then
        echo -e "${RED}❌ No IP provided. Exiting.${NC}"
        exit 1
    fi
fi

PI_SERVER_PORT="${PI_SERVER_PORT:-8000}"
SERVER_URL="http://${PI_SERVER_IP}:${PI_SERVER_PORT}"

echo -e "${BLUE}📡 Server: ${GREEN}${SERVER_URL}${NC}"

# ── Select node type ───────────────────────────────────────
if [ -z "$NODE_TYPE" ]; then
    echo ""
    echo -e "${YELLOW}🤖 Which Pi is this?${NC}"
    echo "   1) Scanner Pi  (Rpi1 — Basil)"
    echo "   2) Solver Pi   (Rpi2 — Luke)"
    echo "   3) Motor Pi    (Rpi3 — Eric)"
    echo ""
    read -p "   Enter 1, 2, or 3: " CHOICE

    case $CHOICE in
        1)
            NODE_ID="rpi1-scanner"
            NODE_TYPE="scanner"
            ;;
        2)
            NODE_ID="rpi2-solver"
            NODE_TYPE="solver"
            ;;
        3)
            NODE_ID="rpi3-motors"
            NODE_TYPE="motor"
            ;;
        *)
            echo -e "${RED}❌ Invalid choice. Exiting.${NC}"
            exit 1
            ;;
    esac
else
    echo ""
    echo -e "${BLUE}🏷️  Node type already configured: ${GREEN}${NODE_TYPE}${NC}"
    echo -e "${YELLOW}   (from .env file)${NC}"
fi

# ── Get Session ID (Scanner Pi only) ────────────────────────
if [ "$NODE_TYPE" = "scanner" ] && [ -z "$SESSION_ID" ]; then
    echo ""
    echo -e "${YELLOW}🔑 Scanner needs a Session ID to post scans.${NC}"
    echo -e "   Find this on the central server's dashboard."
    echo ""
    read -p "   Session ID: " SESSION_ID

    if [ -z "$SESSION_ID" ]; then
        echo -e "${RED}❌ No Session ID provided. Exiting.${NC}"
        exit 1
    fi
fi
export SESSION_ID

NODE_ID="${NODE_ID:-${NODE_TYPE}-node}"
echo -e "${BLUE}🏷️  Node: ${GREEN}${NODE_ID}${NC} (${NODE_TYPE})"

# ── Auto-launch Camera Stream Server (Scanner Pi only) ──────
if [ "$NODE_TYPE" = "scanner" ]; then
    echo ""
    echo -e "${BLUE}🎥 Launching camera stream server...${NC}"
    python3 Scanner/stream_server.py > /tmp/pi3-camera.log 2>&1 &
    CAMERA_PID=$!
    sleep 1
    
    if kill -0 $CAMERA_PID 2>/dev/null; then
        echo -e "   ${GREEN}✓${NC} Camera stream on port 8001"
        echo -e "   ${BLUE}Web UI:${NC} http://localhost:8001"
        echo -e "   ${BLUE}Stream:${NC} http://localhost:8001/video_feed"
    else
        echo -e "   ${YELLOW}⚠${NC}  Camera stream failed to start"
        echo -e "   ${YELLOW}   Check: cat /tmp/pi3-camera.log${NC}"
    fi
fi

# ── Write/update .env ──────────────────────────────────────
cat > .env <<EOF
# Pi³ Node Configuration (auto-generated by start_node.sh)
PI_SERVER_IP=${PI_SERVER_IP}
PI_SERVER_PORT=${PI_SERVER_PORT}
NODE_ID=${NODE_ID}
NODE_TYPE=${NODE_TYPE}
SESSION_ID=${SESSION_ID}
HEARTBEAT_INTERVAL=3
# Motor Pi only:
SERVER_URL=${SERVER_URL}
EOF
echo -e "   ${GREEN}✓${NC} .env written"

# ── Check server is reachable ──────────────────────────────
echo ""
echo -e "${BLUE}🔍 Checking server connection...${NC}"

if command -v curl &> /dev/null; then
    while ! curl -s --connect-timeout 5 "${SERVER_URL}/" > /dev/null 2>&1; do
        echo -e "   ${RED}❌ Cannot reach server at ${SERVER_URL}${NC}"
        echo -e "   ${YELLOW}   Make sure Saim's Pi is running: ./start_server.sh${NC}"
        echo -e "   ${YELLOW}   Waiting for server... retrying in 3s${NC}"
        sleep 3
    done
    echo -e "   ${GREEN}✓${NC} Server reachable at ${SERVER_URL}"
elif command -v wget &> /dev/null; then
    while ! wget -q --timeout=5 --spider "${SERVER_URL}/" 2>/dev/null; do
        echo -e "   ${RED}❌ Cannot reach server at ${SERVER_URL}${NC}"
        echo -e "   ${YELLOW}   Make sure Saim's Pi is running: ./start_server.sh${NC}"
        echo -e "   ${YELLOW}   Waiting for server... retrying in 3s${NC}"
        sleep 3
    done
    echo -e "   ${GREEN}✓${NC} Server reachable at ${SERVER_URL}"
else
    echo -e "   ${YELLOW}⚠${NC}  No curl/wget — skipping connectivity check"
fi

# ── Setup Python venv ──────────────────────────────────────
echo ""
echo -e "${BLUE}🐍 Setting up Python environment...${NC}"

if [ ! -d ".venv" ]; then
    echo "   Creating virtual environment..."
    python3 -m venv .venv
fi

source .venv/bin/activate
pip install -q python-dotenv python-socketio[asyncio_client] httpx requests 2>/dev/null
echo -e "   ${GREEN}✓${NC} Dependencies installed"

# ── Start heartbeat + subsystem ────────────────────────────
echo ""
echo -e "${BLUE}🚀 Starting ${NODE_TYPE} node...${NC}"
echo ""

# Run the heartbeat client alongside the subsystem
python3 -c "
import os, sys, time, threading, requests, subprocess, signal

SERVER = '${SERVER_URL}'
NODE_ID = '${NODE_ID}'
NODE_TYPE = '${NODE_TYPE}'
INTERVAL = 3
PROCESSES = []

def signal_handler(sig, frame):
    print(f'\n🛑 Received signal {sig}. Terminating child processes...')
    for p in PROCESSES:
        try:
            p.terminate()
            p.wait(timeout=2)
        except:
            try: p.kill()
            except: pass
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)

def heartbeat():
    while True:
        try:
            r = requests.post(f'{SERVER}/nodes/heartbeat', json={
                'node_id': NODE_ID,
                'node_type': NODE_TYPE,
                'status': 'online',
            }, timeout=3)
            if r.status_code == 200:
                pass  # silent success
            else:
                print(f'[Heartbeat] Warning: {r.status_code}', file=sys.stderr)
        except requests.ConnectionError:
            print(f'[Heartbeat] Server unreachable — retrying...', file=sys.stderr)
        except Exception as e:
            print(f'[Heartbeat] Error: {e}', file=sys.stderr)
        time.sleep(INTERVAL)

def run_subsystem(command, cwd, env):
    while True:
        try:
            print(f'🚀 Launching {\" \".join(command)} in {cwd}...')
            p = subprocess.Popen(command, cwd=cwd, env=env)
            PROCESSES.append(p)
            p.wait()
            if p in PROCESSES:
                PROCESSES.remove(p)
            print(f'⚠️  Process {\" \".join(command)} exited. Restarting in 5s...')
        except Exception as e:
            print(f'❌ Subsystem Error: {e}', file=sys.stderr)
        time.sleep(5)

if NODE_TYPE == 'scanner':
    SESSION_ID = os.environ.get('SESSION_ID')
    if SESSION_ID:
        env = os.environ.copy()
        env['API_BASE_URL'] = SERVER
        t_sub = threading.Thread(target=run_subsystem, args=([sys.executable, 'scanner_bridge.py'], 'Scanner', env), daemon=True)
        t_sub.start()
    else:
        print(f'⚠️  Warning: SESSION_ID not found in environment. scanner_bridge.py will not start.', file=sys.stderr)
elif NODE_TYPE == 'solver':
    env = os.environ.copy()
    env['API_BASE_URL'] = SERVER
    t_sub = threading.Thread(target=run_subsystem, args=([sys.executable, 'solver_listener.py'], 'solver', env), daemon=True)
    t_sub.start()

# Start heartbeat in background
t_hb = threading.Thread(target=heartbeat, daemon=True)
t_hb.start()
print(f'💓 Heartbeat running for {NODE_ID} ({NODE_TYPE})')
print(f'   Sending to {SERVER}/nodes/heartbeat every {INTERVAL}s')
print(f'   Check dashboard: http://${PI_SERVER_IP}:5173')
print()

print(f'🟢 {NODE_TYPE.title()} node online. Heartbeat active.')
print(f'   Press Ctrl+C to stop.')
print()

# Keep alive — subsystem code would go here
# For scanner: import and run scan loop
# For solver:  import and run solver listener  
# For motor:   import and run motor state machine

# If the subsystem has a main entry point, uncomment the relevant line:
# Scanner:  exec(open('UnitTests/Scanner/test_camera.py').read())
# Motor:    from motorctl.src.main import main; import asyncio; asyncio.run(main())

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    pass
" &
NODE_PID=$!

# ── Print summary ──────────────────────────────────────────
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ ${NODE_TYPE^} node is running!${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BLUE}Server:${NC}     ${SERVER_URL}"
echo -e "  ${BLUE}Node ID:${NC}    ${NODE_ID}"
echo -e "  ${BLUE}Dashboard:${NC}  http://${PI_SERVER_IP}:5173"
echo ""
echo -e "  Press ${RED}Ctrl+C${NC} to stop"
echo ""

# ── Trap Ctrl+C ────────────────────────────────────────────
cleanup() {
    echo ""
    echo -e "${YELLOW}🛑 Shutting down ${NODE_TYPE} node...${NC}"
    kill $NODE_PID 2>/dev/null
    [ -n "$CAMERA_PID" ] && kill $CAMERA_PID 2>/dev/null
    echo -e "${GREEN}   Done. Goodbye!${NC}"
    exit 0
}

trap cleanup SIGINT SIGTERM

wait $NODE_PID
